### ISSUE TITLE
iron excavator recipe Oo

### ISSUE THREAD

**Issue by wackoamd1** [CrimsonFluff/Crimsons-Hammers#2]
dont ask me why every other recipe works perfect and i checked the recipe in the jar but somehow when u want to craft a iron excavator u get a iron lumber axe. and only the iron one the rest just makes the correct item ;-)

on a side note , where are the sickles XD

**Comment by CrimsonFluff** [comment]
the recipe is a bug in rei - I could add a new `tool handle` item, or other tool parts and use them, then I can be more creative with the recipes

sickles aren't done yet - they are dev only

**Comment by wackoamd1** [comment]
weird i didnt know rei could just give u the wrong item , it isnt just the showing of the recipe , even when i just put the items in my crafting grid either left or right way around it just makes a lumber axe. only the iron one does that

**Comment by CrimsonFluff** [comment]
Fair point - it must be minecraft itself - I just assumed rei transferred the items in the wrong order or something

I'll have to add an extra item or two just to make the recipes make sense, and of course actually work

Its weird its that one recipe tho?

**Comment by wackoamd1** [comment]
yeah thats what i thought , i thought maybe u messed up the resulting item in the jar , but it clearly says , excavator_iron , and  it really is just that item that doesnt work

**Comment by CrimsonFluff** [comment]
`i thought maybe u messed up the resulting item in the jar`   you know me so well already  😺   usually I just miss out recipes altogether

**Comment by CrimsonFluff** [comment]
new version is up on CurseForge
