### ISSUE TITLE
MI deepslate not minable

### ISSUE THREAD

**Issue by wackoamd1** [CrimsonFluff/Crimsons-Hammers#3]
Without this basic information your issue will be deleted...

**Basic Mod Information**
Fabric Version : 1.12.2
Mod Version : 1.02
Server, Client or Both : Both

**Describe the bug**
the hammers mine everything except DEEPSLATE modern industrialization ore https://www.curseforge.com/minecraft/mc-mods/modern-industrialization
which is weird because it will mine the standard MI ore , 
and i can  mine the deepslate just fine with a diamond pickaxe but the hammers dont .

**Crash Log**
no crash log it doesnt crash ;-)

**Comment by CrimsonFluff** [comment]
Some reason Fabric moved Minecraft tags, so now have I

Don't rely on the sickles, the mod is undergoing a re-write, starting with Forge
